Repository digitalbitbox/bitbox-base, pull requests merged in 2019-10, with the labels that each got.

#220 middleware: change ToggleSetting rpc message from string to bool
  middleware/src/middleware.go
  middleware/src/middleware_test.go
  middleware/src/rpcmessages/rpcmessages.go
  middleware/src/rpcserver/rpcserver_test.go
  middleware/src/util.go
Labels: P:1

#221 change: RebootBase to run `base restart` and not `base reboot`.
  middleware/src/middleware.go
Labels: P:2, bug

#222 refactor: ErrorResponse Error() method
  middleware/src/rpcmessages/rpcmessages.go
Labels: P:2, enhancement

#225 Middleware: add /version endpoint
  middleware/cmd/middleware/main.go
  middleware/src/handlers/handlers.go
  middleware/src/middleware.go
  middleware/src/system/system.go
  middleware/src/system/system_test.go
Labels: P:2

#223 change: Restart & ShutdownBase without bbb-cmd.sh
  middleware/src/middleware.go
  middleware/src/rpcmessages/errorcodes.go
  middleware/src/util.go
Labels: P:1, bug

#218 middleware: add first version of GetBaseInfo RPC
  middleware/cmd/middleware/main.go
  middleware/src/handlers/handlers.go
  middleware/src/middleware.go
  middleware/src/middleware_test.go
  middleware/src/prometheus/prometheus.go
  middleware/src/prometheus/queries.go
  middleware/src/redis/keys.go
  middleware/src/redis/redis.go
  middleware/src/redis/redis_mock.go
  middleware/src/rpcmessages/errorcodes.go
  middleware/src/rpcmessages/rpcmessages.go
  middleware/src/rpcserver/rpcserver.go
  middleware/src/rpcserver/rpcserver_test.go
  middleware/src/system/system.go
  middleware/src/system/system_test.go
  middleware/src/util.go
Labels: P:2

#231 Middleware: add first version of GetServiceInfo RPC
  middleware/src/handlers/handlers.go
  middleware/src/middleware.go
  middleware/src/prometheus/queries.go
  middleware/src/rpcmessages/rpcmessages.go
  middleware/src/rpcserver/rpcserver.go
  middleware/src/util.go
Labels: P:2

#228 Middleware: add Base update RPCs
  middleware/src/handlers/handlers.go
  middleware/src/middleware.go
  middleware/src/rpcmessages/errorcodes.go
  middleware/src/rpcmessages/rpcmessages.go
  middleware/src/rpcserver/rpcserver.go
  middleware/src/util.go
Labels: P:2
