Repository digitalbitbox/bitbox-base, pull requests merged in 2019-09, with the labels that each got.

#176 Middleware: Add RPCs needed for the base setup
  middleware/.golangci.yml
  middleware/src/handlers/handlers.go
  middleware/src/middleware.go
  middleware/src/middleware_test.go
  middleware/src/rpcmessages/rpcmessages.go
  middleware/src/rpcserver/rpcserver.go
  middleware/src/rpcserver/rpcserver_test.go
Labels: P:1

#178 Middleware: update to current bbb-cmd resync|reindex methods
  middleware/src/middleware.go
Labels: P:1, bug

#180 Middleware: Add Tor RPCs
  middleware/src/handlers/handlers.go
  middleware/src/middleware.go
  middleware/src/middleware_test.go
  middleware/src/rpcserver/rpcserver.go
  middleware/src/rpcserver/rpcserver_test.go
Labels: P:1, waiting for review

#181 Add supervisor error handling
  tools/bbbsupervisor/bbbsupervisor.go
Labels: P:1

#189 middleware: Update hostname restrictions
  middleware/src/middleware.go
  middleware/src/middleware_test.go
  middleware/src/rpcserver/rpcserver_test.go
Labels: P:1

#187 supervisor: add clearnet-ibd finished handling
  tools/bbbsupervisor/bbbsupervisor.go
Labels: P:1

#194 middleware: Add ShutdownBase and RebootBase RPCs
  middleware/src/handlers/handlers.go
  middleware/src/middleware.go
  middleware/src/middleware_test.go
  middleware/src/rpcserver/rpcserver.go
  middleware/src/rpcserver/rpcserver_test.go
Labels: P:2

#204 Prevent flashdrive to mount as /mnt/ssd
  armbian/base/config/redis/factorysettings.txt
  armbian/base/customize-armbian-rockpro64.sh
  armbian/base/scripts/autosetup-ssd.sh
  armbian/base/scripts/systemd-startup-checks.sh
Labels: bug

#196 General update of technical docs
  docs/applications/bitcoin-core.md
  docs/applications/c-lightning.md
  docs/applications/redis.md
  docs/customapps/bbbconfgen.md
  docs/customapps/helper-scripts.md
  docs/hardware.md
  docs/hardware/components.md
  docs/index.md
  docs/os/configuration.md
  docs/os/upgrade.md
  docs/overview/architecture.md
Labels: documentation

#202 Middleware: Error Codes implementation
  middleware/src/middleware.go
  middleware/src/middleware_test.go
  middleware/src/redis/redis.go
  middleware/src/rpcmessages/errorcodes.go
  middleware/src/rpcmessages/rpcmessages.go
  middleware/src/rpcserver/rpcserver_test.go
Labels: P:2

#211 Middleware: Include Flashdrive methods in Backup/Restore Sysconfig
  middleware/src/handlers/handlers.go
  middleware/src/middleware.go
  middleware/src/middleware_test.go
  middleware/src/rpcserver/rpcserver.go
  middleware/src/rpcserver/rpcserver_test.go
  middleware/src/util.go
Labels: P:1
