Repository digitalbitbox/bitbox-base, pull requests merged in 2019-11, with the labels that each got.

#232 Middleware: refactor improve get flashdrive name
  middleware/src/util.go
Labels: P:2, bug

#235 Middleware: add Base firmware update check and notification
  middleware/cmd/middleware/main.go
  middleware/src/handlers/handlers.go
  middleware/src/middleware.go
  middleware/src/redis/redis_mock.go
  middleware/src/rpcmessages/rpcmessages.go
  middleware/src/rpcserver/mocks/Middleware.go
  middleware/src/rpcserver/rpcserver.go
  middleware/src/rpcserver/rpcserver_test.go
  middleware/src/system/system.go
  middleware/src/util.go
  middleware/src/util/semver/semver.go
Labels: P:2

#246 prometheus: prevent bitcoind zero values
  armbian/base/scripts/prometheus-bitcoind.py
Labels: bug

#249 add: read IPC notifications from a named pipe
  middleware/cmd/middleware/main.go
  middleware/src/ipcnotification/ipcnotification.go
  middleware/src/middleware.go
  middleware/src/system/system.go
  middleware/src/system/system_test.go
Labels: P:2

#251 Middleware: handle `mender-update` notification and queue if no client connected
  middleware/src/handlers/handlers.go
  middleware/src/ipcnotification/payloads.go
  middleware/src/middleware.go
  middleware/src/rpcmessages/rpcmessages.go
  middleware/src/util.go
Labels: P:2

#254 add: FinalizeSetupWizard RPC
  middleware/cmd/middleware/main.go
  middleware/go.sum
  middleware/src/handlers/handlers.go
  middleware/src/middleware.go
  middleware/src/middleware_test.go
  middleware/src/rpcmessages/errorcodes.go
  middleware/src/rpcserver/rpcserver.go
  middleware/src/rpcserver/rpcserver_test.go
  middleware/src/system/system.go
  middleware/src/system/system_test.go
  middleware/src/util.go
Labels: P:1

#258 build: don't use bbbmiddleware.conf
  armbian/base/customize-armbian-rockpro64.sh
Labels: bug

#253 docs: restructure and add 'Tinkering' section
  README.md
  docs/applications.md
  docs/applications/bitcoin-core.md
  docs/applications/electrs.md
  docs/customapps.md
  docs/customapps/additional-scripts.md
  docs/customapps/bbb-cmd.md
  docs/customapps/bbb-config.md
  docs/customapps/bbbmiddleware.md
  docs/customapps/go-build.md
  docs/customapps/middleware/middleware-communication.md
  docs/customapps/middleware/middleware-configuration.md
  docs/customapps/middleware/middleware-functionality.md
  docs/hardware.md
  docs/hardware/bbb-schematic.png
  docs/hardware/bitboxbase-components-rendering.png
  docs/hardware/hsm.md
  docs/hardware/hsm/hsm-features.md
  docs/hardware/hsm/hsm-firmware.md
  docs/hardware/hsm/hsm-uart-voltage-decrease.png
  docs/hardware/hsm/hsm-uart-voltage-reading.png
  docs/hardware/hsm/hsm-uart.md
  docs/networking.md
  docs/operating-system.md
  docs/os/armbian-build.md
  docs/os/configuration.md
  docs/os/os-faq.md
  docs/os/security.md
  docs/os/upgrade.md
  docs/os/upgrade_mender_architecture.png
  docs/os/upgrade_mender_process.png
  docs/overview.md
  docs/overview/architecture.md
  docs/overview/diy.md
  docs/start/build-process.md
  docs/tinkering.md
  docs/tinkering/build-ondevice.md
  docs/tinkering/factory-reset.md
  docs/tinkering/overlayroot.md
  docs/tinkering/ssh.md
  docs/ui.md
  docs/ui/bitcoin.md
  docs/ui/lightning.md
  docs/ui/node-management.md
  docs/ui/pairing.md
  docs/ui/rpc.md
  docs/ui/setup.md
  docs/update.md
  docs/update/update-method.md
  docs/update/update-notification.md
  docs/update/update-process.md
  docs/update/update-unsigned.md
  docs/update/update_mender_architecture.png
  docs/update/update_mender_process.png
Labels: documentation

#262 docs: fix broken links
  docs/applications/bitcoin-core.md
  docs/applications/c-lightning.md
  docs/applications/electrs.md
  docs/applications/grafana.md
  docs/os/armbian-build.md
  docs/tinkering.md
Labels: bug, documentation

#261 creating empty bbbmiddleware.conf
  armbian/base/config/templates/bbbmiddleware.conf.template
  armbian/base/customize-armbian-rockpro64.sh
Labels: bug

#269 scripts: remove base:bitcoind-services:enabled
  armbian/base/config/redis/factorysettings.txt
  armbian/base/scripts/bbb-config.sh
Labels: bug

#265 update: re-enable bitcoin services
  armbian/base/scripts/systemd-startup-after-redis.sh
  armbian/base/scripts/systemd-update-checks.sh
Labels: bug

#273 scripts: fix startup check mender.conf
  armbian/base/scripts/systemd-startup-after-redis.sh
  armbian/base/scripts/systemd-startup-checks.sh
Labels: bug

#275 prometheus-base: catch err if pwm1 not present
  armbian/base/scripts/prometheus-base.py
Labels: bug

#278 Fix / improve build process
  Makefile
  armbian/Makefile
  armbian/armbian-build.sh
  armbian/base/customize-armbian-rockpro64.sh
  armbian/base/scripts/bbb-config.sh
  armbian/base/scripts/systemd-startup-checks.sh
Labels: P:1

#274 update technical docs
  bin/go/README.md
  bin/img-mender/README.md
  docs/applications/bitcoin-core.md
  docs/applications/c-lightning.md
  docs/applications/electrs.md
  docs/applications/prometheus.md
  docs/applications/redis.md
  docs/applications/tor.md
  docs/customapps/additional-scripts.md
  docs/customapps/bbb-cmd.md
  docs/customapps/bbbconfgen.md
  docs/hardware.md
  docs/hardware/components.md
  docs/networking.md
  docs/operating-system.md
  docs/os/armbian-build.md
  docs/os/configuration.md
  docs/os/os-faq.md
  docs/os/security.md
  docs/overview.md
  docs/overview/releases.md
  docs/tinkering.md
  docs/tinkering/build-ondevice.md
  docs/tinkering/overlayroot.md
  docs/tinkering/ssh.md
  docs/ui.md
  docs/update/update-method.md
  docs/update/update-notification.md
  docs/update/update-unsigned.md
Labels: documentation
