Repository digitalbitbox/bitbox-base, pull requests merged in 2019-12, with the labels that each got.

#300 Add state and description codes: Part 1
  armbian/base/config/redis/factorysettings.txt
  middleware/go.mod
  middleware/go.sum
  middleware/src/logtags/logtags.go
  middleware/src/redis/keys.go
  middleware/src/redis/redis.go
  middleware/src/redis/redis_mock.go
  tools/bbbsupervisor/go.mod
  tools/bbbsupervisor/go.sum
  tools/bbbsupervisor/redis/redis.go
  tools/bbbsupervisor/supervisor/supervisor.go
  tools/bbbsupervisor/supervisor/util.go
  tools/bbbsupervisor/systemstate/systemstate.go
Labels: P:1

#299 Middleware: Fix and mitigate switched parameters in Configuration factory function
  middleware/cmd/middleware/main.go
  middleware/src/configuration/configuration.go
  middleware/src/configuration/configuration_test.go
  middleware/src/handlers/handlers_test.go
  middleware/src/middleware_test.go
Labels: P:1, bug

#304 build: switch to build production image
  armbian/base/build.conf
  armbian/base/customize-armbian-rockpro64.sh
Labels: build

#297 docs: improve DIY and Releases docs
  docs/overview/diy.md
  docs/overview/releases.md
Labels: documentation

#312 update: reset 'sshpwlogin' on success
  armbian/base/scripts/systemd-update-checks.sh
Labels: bug

#313 docs: middleware and RPC calls
  .gitignore
  docs/customapps/middleware/base-streaming-service-info-changes-to-frontend_sequencediagram-org.svg
  docs/customapps/middleware/middleware-communication.md
  docs/customapps/middleware/middleware-configuration.md
  docs/customapps/middleware/middleware-functionality.md
  docs/customapps/middleware/middleware_ipc_notifications.png
  docs/customapps/middleware/middleware_overview.png
  docs/sources/base-pre-update_sequencediagram-org.txt
  docs/sources/base-streaming-service-info-changes-to-frontend_sequencediagram-org.txt
  docs/sources/base-update-progress-via-rpc_sequencediagram-org.txt
  docs/sources/middleware_ipc_notifications.drawio
  docs/sources/middleware_overview.drawio
  docs/update/base-pre-update_sequencediagram-org.svg
  docs/update/base-update-progress-via-rpc_sequencediagram-org.svg
  docs/update/update-notification.md
  docs/update/update-process.md
  docs/update/update_mender_process.png
Labels: documentation
